### PR TITLE
Update to Unicode 13.0.0

### LINKED ISSUE #28: Update to Unicode version 13
https://www.unicode.org/versions/Unicode13.0.0/

Need to do the following to support the new version:

* Update the unicode database as per the instructions in [this file](https://github.com/harendra-kumar/unicode-transforms/blob/master/unicode-data/README.md)
* Update the [test suite](https://github.com/harendra-kumar/unicode-transforms/blob/master/unicode-data/ucd/NormalizationTest.txt)
* Run tests, fix if something needs to be fixed and commit.

### PR DESCRIPTION
**Pull request by adithyaov**
Closes #28

### CODE REVIEW

**Comment by Bodigrim** [comment]
It seems that some builds have cached an old one, Unicode 12.1 `unicode-data/ucdxml/ucd.all.flat.pdb` and thus fail. Plus the installed `icu` must be the latest, version 66+. Locally all works fine for me.

**Comment by harendra-kumar** [comment]
We are currently using an xml file `ucdxml/ucd.all.flat.zip` for parsing the unicode data. Every time we add a new one it adds to the size of the repository, I am not sure if git is able to create a delta efficiently for this file (.git directory size on my machine is 36 MB). Also, it also takes a lot of time parsing the xml, though it is only a one time job. It contains all the unicode database even a lot of stuff that we do not need.

I am wondering if we should switch to the text files - https://www.unicode.org/Public/13.0.0/ucd/ . That will reduce the size and speed significantly because we need only a few of these and git should be able to handle the incremental changes to these files much more efficiently. It requires some effort and testing though. We can consider this when creating a new package for the data.

**Comment by adithyaov** [comment]
> It seems that some builds have cached an old one, Unicode 12.1 unicode-data/ucdxml/ucd.all.flat.pdb and thus fail. Plus the installed icu must be the latest, version 66+. Locally all works fine for me.

@Bodigrim Since the `pr` CI uses the Github's `merge-commit`, I'm guessing the problem is due to the unpredictability of Github's merge strategy.

**Comment by adithyaov** [comment]
Please note that updating to Unicode 13 did not change anything. The changes are because of executing ucd2haskell before the update.

**Comment by harendra-kumar** [comment]
Why would running ucd2haskell before the update change anything at all? Any changes should come after the update. Maybe you had a newer version .pdb lying around in your workspace when you ran it, it may be from your earlier experiments.

When I run `$ cabal run ucd2haskell -- ucdxml/ucd.all.flat.xml ../Data/Unicode/Properties/` in my workspace, it does not change anything at all.

Can you try cloning the repo in a fresh workspace and run it?

**Comment by adithyaov** [comment]
You're right, I found that strange too. It looks like I messed up.

**Comment by Bodigrim** [comment]
Is there anything unresolved left?

**Comment by adithyaov** [comment]
It should be mergeable now.

**Pull request merged**
