### PR TITLE
Update to Unicode 14.0.0 and unicode-data 0.2

### LINKED ISSUE #73: Update to Unicode 14.0.0
Unicode 14.0.0 has been published on September 14.

See: https://github.com/composewell/unicode-data/pull/36#issuecomment-967099512

### PR DESCRIPTION
**Pull request by wismill**
* Bump `unicode-data`
* Update Unicode 14.0.0 test file

I have tested it with my local copy of 'unicode-data` from master. All 3 tests pass, using `-f has-icu`.

I also propose to bump the version to `0.4` as it is a major change.

Fixes #73

### CODE REVIEW

**Comment by wismill** [comment]
Failing tests due to `unicode-data` 2.0.0 not yet published on Hackage.

I propose to bump the version of `unicode-transforms` to 0.4.0, as this is a major change.

**Comment by harendra-kumar** [comment]
Thank you @wismill ! Looks good to me. Did you try running the benchmarks? We can compare this PR with unicode-data changes against the old release.

> I propose to bump the version of unicode-transforms to 0.4.0, as this is a major change.

yes we can bump the major version.

**Comment by wismill** [comment]
Benchmark (baseline: master):

```
All
  unicode-transforms-text
    NFD/AllChars:    OK (0.40s)
      6.35 ms ± 203 μs
    NFD/Deutsch:     OK (0.89s)
      3.48 ms ±  50 μs
    NFD/Devanagari:  OK (0.70s)
      5.58 ms ± 136 μs
    NFD/English:     OK (0.77s)
      3.01 ms ±  65 μs
    NFD/Japanese:    OK (0.42s)
      6.65 ms ± 195 μs
    NFD/Korean:      OK (3.47s)
      6.74 ms ±  58 μs
    NFD/Vietnamese:  OK (0.41s)
      6.38 ms ± 215 μs,  9% faster than baseline
    NFKD/AllChars:   OK (0.56s)
      8.73 ms ± 204 μs
    NFKD/Deutsch:    OK (0.45s)
      3.55 ms ± 122 μs
    NFKD/Devanagari: OK (0.67s)
      5.24 ms ±  88 μs
    NFKD/English:    OK (0.40s)
      3.12 ms ±  87 μs
    NFKD/Japanese:   OK (0.43s)
      6.84 ms ± 179 μs
    NFKD/Korean:     OK (0.88s)
      6.90 ms ± 114 μs
    NFKD/Vietnamese: OK (0.42s)
      6.87 ms ± 271 μs
    NFC/AllChars:    OK (0.31s)
      9.81 ms ± 338 μs,  3% slower than baseline
    NFC/Deutsch:     OK (0.49s)
      3.80 ms ± 119 μs
    NFC/Devanagari:  OK (0.80s)
      6.44 ms ± 115 μs
    NFC/English:     OK (0.74s)
      2.87 ms ± 100 μs
    NFC/Japanese:    OK (0.64s)
      10.0 ms ± 168 μs
    NFC/Korean:      OK (1.13s)
      4.44 ms ±  52 μs
    NFC/Vietnamese:  OK (0.44s)
      14.7 ms ± 354 μs
    NFKC/AllChars:   OK (0.47s)
      14.9 ms ± 357 μs
    NFKC/Deutsch:    OK (0.64s)
      4.98 ms ± 196 μs
    NFKC/Devanagari: OK (0.42s)
      6.68 ms ± 256 μs
    NFKC/English:    OK (0.40s)
      3.15 ms ± 116 μs
    NFKC/Japanese:   OK (0.74s)
      11.8 ms ± 244 μs
    NFKC/Korean:     OK (0.34s)
      5.45 ms ± 196 μs
    NFKC/Vietnamese: OK (0.93s)
      14.7 ms ± 196 μs

All 28 tests passed (19.94s)
```

**Comment by harendra-kumar** [comment]
unicode-data 0.2.0 is published hackage.

**Comment by harendra-kumar** [comment]
We can add GHC 9.2 to the CI config before we release. Some CIs are failing. Need to change stack lts/extra deps in the stack/windows CIs. It seems hashable build is failing for 7.10.3.

**Comment by adithyaov** [comment]
@wismill Can you please update the stack config to have `unicode-data-0.2.0` instead of `unicode-data-0.1.0.1` to satisfy the CIs?

**Comment by wismill** [comment]
@adithyaov Done

**Comment by harendra-kumar** [comment]
@wismill there are some conflicts due to the text PR merge. Can you please rebase it again? Yes, please bump the version to 0.4.0.

**Comment by wismill** [comment]
@harendra-kumar Done. I also included a mention of the update of `text` in the changelog.

**Comment by harendra-kumar** [comment]
Thanks for all the effort @wismill ! Looks good to me. We can merge it and upload the release to hackage unless @Bodigrim @adithyaov have something to say.

**Comment by adithyaov** [comment]
Great work @wismill! There was a CI error earlier, it looks unrelated to the changes in this PR though. I've re-run the CIs. We can merge it once the CIs pass.

**Comment by adithyaov** [comment]
We can ignore the CI error for now. @harendra-kumar Any idea on how to solve the problem?

**Review by adithyaov — APPROVED** [review]

**Review by Bodigrim — APPROVED** [review]

**Comment by harendra-kumar** [comment]
I will ignore the 7.10.3 failure and merge this. Let's upload this to hackage.

**Pull request merged**
