### PR TITLE
Use raw bitmaps

### PR DESCRIPTION
**Pull request by Bodigrim**
Switching from `bitarray` to raw bitmaps `Addr#` significantly improves Japanese, Vietnamese, AllChars and Devanagari benchmarks. 

```
Benchmark         Before     After
------------------------------------
NFD/Japanese     34.66 ms   18.49 ms
NFD/Vietnamese   19.84 ms   15.95 ms
NFD/AllChars     23.21 ms   20.57 ms
NFD/Deutsch      12.11 ms   12.36 ms
NFD/English      10.99 ms   10.05 ms
NFD/Devanagari   25.17 ms   15.24 ms
NFD/Korean       32.23 ms   32.56 ms
NFKD/Japanese    35.74 ms   20.14 ms
NFKD/Vietnamese  20.45 ms   17.79 ms
NFKD/AllChars    29.91 ms   22.83 ms
NFKD/Deutsch     11.75 ms   12.30 ms
NFKD/English     10.62 ms   10.71 ms
NFKD/Devanagari  25.04 ms   15.32 ms
NFKD/Korean      32.25 ms   32.27 ms
NFC/Japanese     96.72 ms   75.07 ms
NFC/Vietnamese   71.86 ms   70.28 ms
NFC/AllChars     71.56 ms   62.54 ms
NFC/Deutsch      65.41 ms   66.58 ms
NFC/English      62.87 ms   63.01 ms
NFC/Devanagari   71.23 ms   58.19 ms
NFC/Korean       53.74 ms   54.01 ms
NFKC/Japanese    103.8 ms   80.00 ms
NFKC/Vietnamese  73.16 ms   69.92 ms
NFKC/AllChars    87.15 ms   77.18 ms
NFKC/Deutsch     66.76 ms   66.69 ms
NFKC/English     64.34 ms   63.61 ms
NFKC/Devanagari  73.95 ms   59.96 ms
NFKC/Korean      54.07 ms   53.91 ms
```
Travis builds fail for independent reasons AFAICT.

### CODE REVIEW

**Comment by harendra-kumar** [comment]
Looks great! Thank you. I will take a better look at the change later.

**Comment by Bodigrim** [comment]
The background is that I ran `stack bench --profile +RTS -p` and it appeared that `bitarray` eats ~30% of time and ~50% of allocations:

```
COST CENTRE           SRC                                       %time %alloc
----------------------------------------------------------------------------
unsafeLookupBit       Data/BitArray.hs:(57,1)-(59,9)             13.6    0.0
ind                   Data/BitArray/Immutable.hs:(24,1)-(26,22)  11.4   30.0
lookupBit             Data/BitArray.hs:(52,1)-(54,27)             4.1   10.9
unsafeLookupBit.w     Data/BitArray.hs:59:3-9                     1.4    5.5
unsafeLookupBit.(...) Data/BitArray.hs:58:3-19                    1.1    0.0
```

Since you need only a static bitmask, fully known at compile time, it is beneficial to cut the middle man completely and bake masks into pregenerated `Addr#` literals. Anyways, these source files are autogenerated by `ucd2haskell`. 

Now `stack bench --profile +RTS -p` looks much more reasonable:

```
COST CENTRE           SRC                                                          %time %alloc
-----------------------------------------------------------------------------------------------
normalize           Data/Text/Normalize.hs:(31,1)-(36,48)                           69.9   91.1
isHangul            Data/Unicode/Properties/DecomposeHangul.hs:(62,1)-(63,19)        6.9    0.0
isJamo              Data/Unicode/Properties/DecomposeHangul.hs:(72,1)-(73,19)        4.1    0.0
combiningBitmap     Data/Unicode/Properties/CombiningClass.hs:(883,1)-(887,62491)    3.2    0.0
composePair         Data/Unicode/Properties/Compositions.hs:(9,1)-(950,25)           3.1    0.0
decomposeBitmap     Data/Unicode/Properties/DecomposableK.hs:(16,1)-(20,97316)       2.6    0.0
decomposeBitmap     Data/Unicode/Properties/Decomposable.hs:(16,1)-(20,97390)        2.2    0.0
decomposeCharHangul Data/Unicode/Internal/NormalizeStream.hs:(73,1)-(83,44)          1.4    1.6
writeStarterRbuf    Data/Unicode/Internal/NormalizeStream.hs:(298,1)-(303,72)        0.9    2.2
```

**Comment by harendra-kumar** [comment]
After your change this is how we compare with `icu`, the C++ library. The second column is:

* When +ve -  by what percentage is unicode-transforms timing more than ICU
* When -ve - by what percentage is ICU timing more than unicode-transforms

```
(time)
Benchmark       ICU(ms)(base) unicode-transforms(%)(-base)
--------------- ------------- ----------------------------
NFD/AllChars             8.94                       +14.82
NFD/Deutsch              3.61                       +74.59
NFD/Devanagari           9.37                       +20.26
NFD/English              2.97                       +92.43
NFD/Japanese            10.74                       +21.69
NFD/Korean              38.48                       -47.17
NFD/Vietnamese           7.21                       +28.98

NFKD/AllChars           11.30                       +37.35
NFKD/Deutsch             3.68                       +75.39
NFKD/Devanagari          9.34                       +16.43
NFKD/English             2.90                      +106.07
NFKD/Japanese           10.48                       +34.70
NFKD/Korean             38.95                       -47.23
NFKD/Vietnamese         13.36                       -23.56
```

Decompositions are not bad. Compositions are much worse because that's not yet optimized even algorithmically:

```
(time)
Benchmark       ICU(ms)(base) unicode-transforms(%)(-base)
--------------- ------------- ----------------------------
NFC/AllChars             3.87                      +965.82
NFC/Deutsch              2.19                     +1754.27
NFC/Devanagari           8.65                      +367.46
NFC/English              2.13                     +1770.08
NFC/Japanese             3.03                     +1671.52
NFC/Korean               4.60                      +832.27
NFC/Vietnamese          17.73                      +142.78

NFKC/AllChars           10.58                      +379.08
NFKC/Deutsch             3.40                     +1110.38
NFKC/Devanagari          8.79                      +357.29
NFKC/English             1.97                     +1859.51
NFKC/Japanese            6.20                      +831.79
NFKC/Korean              7.86                      +429.20
NFKC/Vietnamese         20.09                      +114.66
```

**Comment by Bodigrim** [comment]
If you are happy with this PR, I have more performance improvements in stash :)

**Comment by harendra-kumar** [comment]
> If you are happy with this PR, I have more performance improvements in stash :)

I love it. What else do you have in store? I made a few changes on top of your change and improved it a bit more. Not sure if we both made the same changes. I will merge this one and create a PR with my changes, you can review that, and please add another PR with your changes.

I will take a look at the CI failures, it seems the script was not able to install `stack`, its packaging may have changed. `cabal` builds are succeeding.

**Comment by harendra-kumar** [comment]
Merging this, CI fix is coming soon.

**Comment by adithyaov** [comment]
Please note that updating to Unicode 13 did not change anything. The changes are because of executing `ucd2haskell` before the update.

**Pull request merged**
