### PR TITLE
Fix x32 build

### PR DESCRIPTION
**Pull request by Bodigrim**
CC @simonmichael @blackgnezdo

### CODE REVIEW

**Review by harendra-kumar — APPROVED** [review]
Looks good. Did you check the benchmarks?

Would be nice if you can upload a minor release to Hackage. If you are busy, let me know and I will do it.

**Comment by Bodigrim** [comment]
Do you prefer 0.3.7.1 or 0.3.8.0?

**Comment by harendra-kumar** [comment]
No preference, you decide.

**Comment by Bodigrim** [comment]
0.3.7.1 then.
@harendra-kumar once you merge this PR, I'll release it on Hackage.

**Comment by harendra-kumar** [comment]
You can wait for #56 before you upload. Also push a tag v0.3.7.1 to the repo after you upload.

**Pull request merged**
