### PR TITLE
Update to Unicode 12.1.0. Fix #19

### LINKED ISSUE #19: Support unicode 10
http://www.unicode.org/versions/Unicode10.0.0/

Its easy to support it:

* Update the unicode database as per the instructions in [this file](https://github.com/harendra-kumar/unicode-transforms/blob/master/unicode-data/README.md)
* Update the [test suite](https://github.com/harendra-kumar/unicode-transforms/blob/master/unicode-data/ucd/NormalizationTest.txt)
* Run tests, fix if something needs to be fixed and commit.

### PR DESCRIPTION
**Pull request by wismill**
- [x] Update the unicode database as per the instructions in [this file](../tree/master/unicode-data/README.md)
- [x] Update the test suite
- [x] Run tests, fix if something needs to be fixed and commit.

### CODE REVIEW

**Comment by harendra-kumar** [comment]
@wismill thanks for the update. The changes look good to me. There are a few more things that need to be done before we can make a release, can you please also take care of the following while you are at it:

* Update the changelog mentioning the unicode version supported
* Update the README, currently it mentions unicode 9.0
* Running `packdeps` on unicode-transforms.cabal says quickcheck dependency needs to be upgraded so that Quickcheck-2.13.1 can be accepted. We need to change the version bounds in the cabal file.
* Update the resolver in stack.yaml to the latest resolver
* Update GHC version from 8.6.2 to 8.6.5 in .travis.yml, also change the OSX build to latest resolver
* Change the resolver to latest in appveyor.yml
* Change the tested-with field in .cabal file to 8.6.5

Can you also try running the benchmarks before and after to see if there is any significant regression. I do not expect any regression with these changes, but still its good to measure. Thanks a lot for your time and effort in doing this.

If you are interested I can add you as a maintainer for any future upgrades.

**Comment by wismill** [comment]
I have done the modifications. As for the the benchmarks (`cabal v2-bench`), do you have a handy tool to compare them?

**Comment by harendra-kumar** [comment]
Added benchmark regression checking/reporting tool via #21. Once I merge that you can rebase your branch with master and use it.

**Comment by harendra-kumar** [comment]
@wismill merged PR #21 . See the README.md file in the benchmark directory to use the comparing tool.

**Comment by wismill** [comment]
There does not appear to be an option `--append` for the benchmark:
```
$ cabal v2-run bench -- --csvraw=results3.csv --append unicode-transforms
Up to date
bench: unrecognized option `--append'
Microbenchmark suite - built with gauge 0.2.4
  -I CI     --ci=CI                   Confidence interval
  -G        --no-gc                   Do not collect garbage between iterations
  -L SECS   --time-limit=SECS         Min seconds for each benchmark run, default is 5.0 in normal mode, 0.0 in quick mode
            --min-samples=COUNT       Min no. of samples for each benchmark, default is 10 in normal mode, 1 in quick mode
            --min-duration=MILLISECS  Min duration for each sample, default is MilliSeconds 30, when 0 stops after first iteration
            --include-first-iter      Do not discard the measurement of the first iteration
  -q        --quick                   Perform a quick measurement and report results without statistical analysis
            --measure-only=FILE       Just measure the benchmark and place the raw data in the given file
            --measure-with=FILE       Perform measurements in a separate process using this program.
            --resamples=COUNT         Number of boostrap resamples to perform
            --regress=RESP:PRED..     Regressions to perform
            --raw=FILE                File to write raw data to
  -o FILE   --output=FILE             File to write report to
            --csvraw=FILE             File to write CSV measurements to
            --csv=FILE                File to write CSV summary to
            --json=FILE               File to write JSON summary to
            --junit=FILE              File to write JUnit summary to
  -v LEVEL  --verbosity=LEVEL         Verbosity level
  -t FILE   --template=FILE           Template to use for report
  -n ITERS  --iters=ITERS             Run benchmarks, don't analyse
  -m MATCH  --match=MATCH             Benchmark match style: prefix (default), exact, pattern (substring), or ipattern (case insensitive)
  -l        --list                    List benchmarks
            --version                 Show version info
  -s        --small                   Set benchmark display to the minimum useful information
  -h        --help                    Show help

CallStack (from HasCallStack):
  error, called at ./Gauge/Main/Options.hs:273:17 in gauge-0.2.4-dbcf496f5e89ff752095d6ae1dd40eeb566d32652c6602b318454ea5e5b84598:Gauge.Main.Options
```

**Comment by wismill** [comment]
Master:
```
Benchmark  unicode-transforms(ms)
---------- ----------------------
English                      7.19
Deutsch                      8.03
Vietnamese                  13.37
Korean                      14.21
AllChars                    17.04
Devanagari                  17.99
Japanese                    25.68

(maxrss)
Benchmark  unicode-transforms(KiB)
---------- -----------------------
AllChars                     30.28
Deutsch                      31.87
Devanagari                   32.00
English                      32.66
Japanese                     32.66
Korean                       32.66
Vietnamese                   32.66
```

This PR:
```
Benchmark  unicode-transforms(ms)
---------- ----------------------
English                      7.26
Deutsch                      8.02
Vietnamese                  13.44
Korean                      14.08
AllChars                    16.61
Devanagari                  16.87
Japanese                    24.95

(maxrss)
Benchmark  unicode-transforms(KiB)
---------- -----------------------
AllChars                     28.99
Deutsch                      29.66
Devanagari                   30.69
English                      32.58
Japanese                     32.58
Korean                       36.07
Vietnamese                   36.26
```

**Comment by harendra-kumar** [comment]
Sorry about that. Yes there is no `--append` option it appends by default. So you can just run it without that option, the results will be appended to the csv file and then when you run the chart executable it will show the diffs between the two runs.

**Comment by wismill** [comment]
```
Benchmark  unicode-transforms(0)(ms)(base) unicode-transforms(1)(%)(-base)
---------- ------------------------------- -------------------------------
English                               7.60                           +1.92
Deutsch                               8.28                           -0.33
Vietnamese                           13.60                           +0.29
Korean                               14.12                           -0.15
Devanagari                           17.48                           +0.73
AllChars                             17.79                           -2.82
Japanese                             30.03                          -12.41

(maxrss)
Benchmark  unicode-transforms(0)(KiB)(base) unicode-transforms(1)(%)(-base)
---------- -------------------------------- -------------------------------
AllChars                             215.86                          -16.30
Deutsch                              215.86                          -16.30
Devanagari                           215.86                          -16.30
English                              215.86                          -16.30
Japanese                             215.86                          -16.30
Korean                               215.86                          -16.30
Vietnamese                           215.86                          -16.30
```

**Comment by harendra-kumar** [comment]
@wismill thanks for all the work! Much appreciated. I like the simplified benchmark running instructions. We need to get it up on Hackage now, maybe after a few days of soak time.

**Pull request merged**
